// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/derailleur.proto

package derailleur

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDerailleurRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameId      string `protobuf:"bytes,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Manufacturer string `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Speed        string `protobuf:"bytes,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Model        string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *CreateDerailleurRequest) Reset() {
	*x = CreateDerailleurRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_derailleur_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDerailleurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDerailleurRequest) ProtoMessage() {}

func (x *CreateDerailleurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_derailleur_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDerailleurRequest.ProtoReflect.Descriptor instead.
func (*CreateDerailleurRequest) Descriptor() ([]byte, []int) {
	return file_proto_derailleur_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDerailleurRequest) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *CreateDerailleurRequest) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *CreateDerailleurRequest) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

func (x *CreateDerailleurRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type CreateDerailleurResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Derailleur *BikeDerailleur `protobuf:"bytes,1,opt,name=derailleur,proto3" json:"derailleur,omitempty"`
}

func (x *CreateDerailleurResponse) Reset() {
	*x = CreateDerailleurResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_derailleur_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDerailleurResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDerailleurResponse) ProtoMessage() {}

func (x *CreateDerailleurResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_derailleur_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDerailleurResponse.ProtoReflect.Descriptor instead.
func (*CreateDerailleurResponse) Descriptor() ([]byte, []int) {
	return file_proto_derailleur_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDerailleurResponse) GetDerailleur() *BikeDerailleur {
	if x != nil {
		return x.Derailleur
	}
	return nil
}

type BikeDerailleur struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FrameId      string `protobuf:"bytes,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Manufacturer string `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Speed        string `protobuf:"bytes,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Model        string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *BikeDerailleur) Reset() {
	*x = BikeDerailleur{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_derailleur_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BikeDerailleur) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikeDerailleur) ProtoMessage() {}

func (x *BikeDerailleur) ProtoReflect() protoreflect.Message {
	mi := &file_proto_derailleur_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BikeDerailleur.ProtoReflect.Descriptor instead.
func (*BikeDerailleur) Descriptor() ([]byte, []int) {
	return file_proto_derailleur_proto_rawDescGZIP(), []int{2}
}

func (x *BikeDerailleur) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BikeDerailleur) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *BikeDerailleur) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *BikeDerailleur) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

func (x *BikeDerailleur) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_proto_derailleur_proto protoreflect.FileDescriptor

var file_proto_derailleur_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65,
	0x75, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x69, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x22, 0x84, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x72, 0x61,
	0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75,
	0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x53, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x64, 0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65,
	0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x69, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x44, 0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75,
	0x72, 0x52, 0x0a, 0x64, 0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72, 0x22, 0x8b, 0x01,
	0x0a, 0x0e, 0x42, 0x69, 0x6b, 0x65, 0x44, 0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6d,
	0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x32, 0x65, 0x0a, 0x0a, 0x44,
	0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72, 0x12, 0x57, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72, 0x12, 0x20, 0x2e,
	0x62, 0x69, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x62, 0x69, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x64, 0x65,
	0x72, 0x61, 0x69, 0x6c, 0x6c, 0x65, 0x75, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_derailleur_proto_rawDescOnce sync.Once
	file_proto_derailleur_proto_rawDescData = file_proto_derailleur_proto_rawDesc
)

func file_proto_derailleur_proto_rawDescGZIP() []byte {
	file_proto_derailleur_proto_rawDescOnce.Do(func() {
		file_proto_derailleur_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_derailleur_proto_rawDescData)
	})
	return file_proto_derailleur_proto_rawDescData
}

var file_proto_derailleur_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_derailleur_proto_goTypes = []interface{}{
	(*CreateDerailleurRequest)(nil),  // 0: bicycle.CreateDerailleurRequest
	(*CreateDerailleurResponse)(nil), // 1: bicycle.CreateDerailleurResponse
	(*BikeDerailleur)(nil),           // 2: bicycle.BikeDerailleur
}
var file_proto_derailleur_proto_depIdxs = []int32{
	2, // 0: bicycle.CreateDerailleurResponse.derailleur:type_name -> bicycle.BikeDerailleur
	0, // 1: bicycle.Derailleur.CreateDerailleur:input_type -> bicycle.CreateDerailleurRequest
	1, // 2: bicycle.Derailleur.CreateDerailleur:output_type -> bicycle.CreateDerailleurResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_derailleur_proto_init() }
func file_proto_derailleur_proto_init() {
	if File_proto_derailleur_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_derailleur_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDerailleurRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_derailleur_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDerailleurResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_derailleur_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BikeDerailleur); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_derailleur_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_derailleur_proto_goTypes,
		DependencyIndexes: file_proto_derailleur_proto_depIdxs,
		MessageInfos:      file_proto_derailleur_proto_msgTypes,
	}.Build()
	File_proto_derailleur_proto = out.File
	file_proto_derailleur_proto_rawDesc = nil
	file_proto_derailleur_proto_goTypes = nil
	file_proto_derailleur_proto_depIdxs = nil
}
